### PR TITLE
Updated BCM94352Z as BCM94360CS2

### PR DESCRIPTION
**Pull request by robvanoostenrijk**
As suggested on the forum, now the injector is making use of AppleMergeUSBNub.

This happens only when the device-id has not been changed through DSDT or Clover fake-id.
AppleMergeNub will overwrite the device-id, vendor-id etc.
Additionally the Airport_Brcm4360 driver is matched with a separate IOKitPersonality to ensure it loads for 14e4:43b1.

So in short, the same injector kext now works with or without device-id injected.

### CODE REVIEW

**Comment by robvanoostenrijk** [comment]
Added Intel HDMI Audio injector.

This injects `8086:0c0c` as `8086:0d0c` so that it is natively recognised by OS X.
Additionally it adds the `hda-gfx = <"onboard-1">` property.

Interestingly `PinConfigurations` and `layout-id` are set automatically by OS X.
The overrides for those are present, but disabled by default.

**Comment by RehabMan** [comment]
I merged everything here, but changed the build products back to build/Products/Debug|Release.  There are problems if you try to set it to build/Debug|Release.  Sometimes xcode will still place builds in build/Products as if something is hard-coded somewhere... which then leads to confusion.

And the makefile wasn't updated for the path change anyway...

I'm slowly changing all my projects to use build/Products to avoid this problem as I visit them...

**Comment by RehabMan** [comment]
Note: I'm really very surprised that a "device-id" inject by kext (AppleUSBMergeNub) can be effective for IOKit matching, since it should have already been done by the time kexts are loading...

I'll have to experiment with it.

My guess is the "device-id" inject via AppleUSBMergeNub isn't really doing anything as far as IOKit matching and you could just as well substitute "RM,device-id".  Getting the kext to load can be done with a codeless kext.

**Comment by robvanoostenrijk** [comment]
AppleUSBMergeNub is indeed not effective for IOKit matching, the passive IOKit matching will already have been done.

For the BCM94352Z I support the original device without DSDT patch by injecting the driver reference with a new IOPCIPrimaryMatch directly into our plist (codeless kext as you suggest).

For the Intel HDMI Audio, the original driver uses a PCI class match, so no driver injection is required.
However AppleHDADriver does read the device ID from the pci config space internally and decides things based on it (hence the Clover patches), now FakePCIID takes care of that in a clean way.

The AppleUSBMergeNub in both cases is only used to provide a new device-id, vendor-id etc for FakePCIID to read and provide back when read from the pci configuration space.
(And some additional properties in case of Intel HDMI Audio)

It could be done through RM,device-id instead, but I'd rather have IORegistry and FakePCIID return the same values.

We could "bump" the AppleUSBMergeNub IOProbeScore to a higher number so its always the first selected driver and executes its probe first. Since AppleUSBMergeNub runs in the default IOMatchCategory, that way the properties are merged as early as possible, before the normal driver loads.

**Comment by RehabMan** [comment]
> "It could be done through RM,device-id instead, but I'd rather have IORegistry and FakePCIID return the same values."

Interesting... I'd rather see the opposite, as it gives a clearer picture of what is going on when you're looking at someone's ioreg.  :-)

**Comment by robvanoostenrijk** [comment]
Ok, I will test for you if that works ok.

**Pull request merged**
