### PR TITLE
Master

### PR DESCRIPTION
**Pull request by syscl**
Add support for Dell Wireless 1707 (DW1707):
1. Chip: QCA9565
2. Bluetooth: 4.0
3. Bands: 802.11b/g/n  2.4GHz
4. A cheap M2 WI-Fi

### CODE REVIEW

**Comment by RehabMan** [comment]
What is the point here?
Are you saying you just want to add the id of AR9565 and that you're rebranding an AR9280?
Or are you saying the stock kext works by treating an actual AR9565 as AR9280?

**Comment by syscl** [comment]
Right, by rebranding AR9569 as AR9280, we can power up DW 1707 by stock kext.

syscl

**Comment by RehabMan** [comment]
Rebranding involves changing the values in EEPROM on the WiFi card.  I assume that's not what you did...

Perhaps you should clearly explain what you're actually doing.

**Comment by syscl** [comment]
I mean adding "pci168c,36" in injector AR9280_as_AR946x.plist can power up the DW 1707. 

syscl

**Comment by the-braveknight** [comment]
You really mean that the AR9565 can work on macOS if treated as AR9280...? I have this card, maybe I should try by myself...

**Comment by lousia** [comment]
@the-braveknight you should try, it did work! I have DW 1707 on my laptop. 

Without syscl's patch, I have to edit plist to add ```pci168c,36``` to power it up, but when compile and use syscl's patch, I do not need to touch the original kext any more.

**Comment by the-braveknight** [comment]
I am not home at the moment, but I'd be thankful if you could post a photo, you just made me excited to try it! :D

**Comment by the-braveknight** [comment]
Well many users are reporting success with this card, but I'm not able to enable it... the kext just wouldn't attach to the card... any ideas? @RehabMan?

**Comment by the-braveknight** [comment]
Well it did work! But required extra efforts and messing with system kexts... I couldn't get it to work until I followed this video: https://www.youtube.com/watch?v=4Q_bLKSCFDU
It required me to delete the stock IO80211 kext and corecapture.kext and install modified versions of them. I hope @RehabMan can take a look and try to add AR9565 support to FakePCIID without messing with system kexts because this card is widely used by Lenovo laptops, and so users won't have to patch their BIOS because it's already whitelisted in most Lenovo BIOSes.

**Comment by RehabMan** [comment]
I'll need to order an AR9565 and test it before adding to FakePCIID.
Also, FakePCIID_AR9280_as_AR946x.kext is not the correct place to put this...
This should be a separate injector kext, named appropriately.

**Comment by syscl** [comment]
I am old school, so I just added ```pci168c,36``` in ```IONameMatch``` in ```AirPortAtheros40.kext```/Contents/```Info.plist``` , that's it.

syscl

**Comment by the-braveknight** [comment]
What version of macOS/OS X are you running?

**Comment by RehabMan** [comment]
>  so I just added pci168c,36 in IONameMatch in AirPortAtheros40.kext/Contents/Info.plist , that's it.

Then no need for FakePCIID if support is already in the kext.
I would probably tend to add it to ProbookAtheros.kext instead (it is just a codeless kext).

But if you also needed FakePCIID to spoof the PCI ID, then that is something else entirely.  If that is the case, then there should be also a personality added to cause the native kext to load in the FakePCIID injector Info.plist.

I won't be able to check this for a while.  If someone wants to fill in the missing details... that would be great.

**Comment by the-braveknight** [comment]
I'll try to do some testing and report back. 
I couldn't get it to work until I replaced IO80211 kext with a patched one... but I'll try again soon when I have time.
But isn't that just weird? I mean how can an AR956x card work in OS X with the same AR9280 driver...? @.@

**Comment by RehabMan** [comment]
Try with ProBookAtheros.kext with this diff:
```
--- a/kexts/ProBookAtheros.kext/Contents/Info.plist
+++ b/kexts/ProBookAtheros.kext/Contents/Info.plist
@@ -36,6 +36,7 @@
                        <array>
                                <string>pci168c,2e</string>
                                <string>pci168c,2b</string>
+                               <string>pci168c,36</string>
                        </array>
                        <key>IOProbeScore</key>
                        <integer>600</integer>
```

Use vanilla IO80211Family.kext.

It is possible that support was added to the kext binary but Apple didn't advertise the support in the Info.plist.

**Comment by the-braveknight** [comment]
Well I tried that but it didn't work. It never worked without the kexts linked in here: https://www.youtube.com/watch?v=4Q_bLKSCFDU

**Comment by cuong95nddev** [comment]
@syscl the kext for Dell Wireless 1707 (DW1707) is now working? and the Bluetooth is working too?

**Comment by RehabMan** [comment]
My understanding is the idea proposed here doesn't work.
Closing this issue.

**Pull request closed without merging**
